### PR TITLE
upgrade buffalo v0.12.1

### PR DESCRIPTION
**Pull request by drnic**

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Also hit authrecipe as well or should I do that so you can focus on other stuff?

**Comment by robbyoconnor** [comment]
Great work by the way <3

**Comment by drnic** [comment]
Sure, https://github.com/gobuffalo/authrecipe/pull/10 BTW I did the upgrade because I just happened to be trying to get gothrecipe working yesterday to learn about goth; and it was sitting in my terminal this morning after 0.12.1 dropped :)

**Comment by drnic** [comment]
I've also now changed `Gopkg.toml` to specifically 0.12.1 rather than development branch, like authrecipe.

**Pull request merged**
